### Create New Service for User
POST https://127.0.0.1:3000/service/12345
Content-Type: application/json
Accept: application/json

{
  "srv_name": "My Service",
  "srv_type": "Basic",
  "desc": "A test service",
  "photo": "https://example.com/photo.jpg",
  "owner_id": "12345",
  "owner_name": "Swan Htet"
}
