server:
  name: "asauth"
  idle_timeout: 30        # seconds
  read_timeout: 15        # seconds
  write_timeout: 15       # seconds
  shutdown_timeout: 5     # seconds
  addr: "0.0.0.0:8004"
  allowed:
    origin: "http://localhost:8808"
  jwt: "5p3+1iIUsCP8Lc6t2FG+wWHre12WSSlS8VQDuCCdhhE="
  cert_file: "./certificates/cert.pem"
  key_file:  "./certificates/key.pem"

database:
  dsn: "postgres://postgres:postgres@postgres:5432/auth?sslmode=disable"

nats:
  url: "nats://dummy:dummy@nats:4222"
  max_reconnects: 5
  reconnect_wait_seconds: 2
  timeout_seconds: 10
resend:
  api:
    key: re_9jUsKjRx_LGLEWtsr1USfy8bJQkXchW16
redis:
  addr: "redis:6379"  # Changed from localhost to redis (Docker service name)
  password: ""        # Empty if no password
  db: 0

front-end:
  redirect:
    forgot-password: http://localhost:3000/forgot-password
    reset-password: http://localhost:3000/reset-password

