// For User DashBoard
GET https://localhost:8081/api/service/:userId


###
POST https://localhost:8081/api/service
Content-Type: application/json

{
  // user service payload
}

###
PUT  https://localhost:8081/api/services&userId=UUUU#WRJJ-&serviceId=12233


###
DELETE  https://localhost:8081/api/services?serviceId=fdafads?userId=1fdfas
