
POST http://localhost:8085/api/auth/register
Content-Type: application/json

{
  "fullname": "Swan Htet Aung",
  "email": "swanhtetaungp@gmail.com",
  "country": "USA",
  "biometric_hash": "123456dfafsdiiiads789abcdef",
  "password": "securepassword123",
  "timestamp": 1679987456
}


###
POST http://localhost:8085/api/auth/verify
Content-Type: application/json

{
  "email": "swanhtetaungp@gmail.com",
  "code": "628612"
}



###
POST  http://localhost:8085/api/auth/login
Content-Type: application/json

{
  "email": "swanhtetaungp@gmail.com",
  "password": "securepassword123"
}

####
#thService git:(main) ✗ docker exec -it vault \
#vault login \
#-address="http://127.0.0.1:8200" \
#-method=token \
#token="KZc3qNSpLXzIz7h6UV7/7ZzPxqWmqEUk8X0aW3J3F8M="
#const demoAddress = "7dCZzk2XdsGSsXtnwtRjZXXXzR4B4DQ6cWzZeML9SSto"
###
POST  http://localhost:8085/api/auth/wallet
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkZXZpY2UiOnsiYnJvd3NlciI6InVua25vd24iLCJkZXRlY3RlZF9hdCI6IjIwMjUtMDQtMTFUMTI6MTA6NTguOTY1MzYzKzAyOjAwIiwiZGV2aWNlX3R5cGUiOiJkZXNrdG9wIiwiZmlyc3RfbG9naW4iOiIyMDI1LTA0LTExVDEyOjEwOjU4Ljk2NTM2MyswMjowMCIsImxhc3RfbG9naW4iOiIyMDI1LTA0LTExVDEyOjEwOjU4Ljk2NTM2MyswMjowMCIsIm9zIjoidW5rbm93biJ9LCJlbWFpbCI6InN3YW5odGV0YXVuZ3BAZ21haWwuY29tIiwiZXhwIjoxNzQ0MzY3MTU4LCJpYXQiOjE3NDQzNjYyNTgsInJvbGUiOiJhY2Nlc3MiLCJzdWIiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDAifQ.6XCCLGmL9OnI7RfSmQlmB-cUJw2w8fqJR7GvhcxsXIA

{
  "userid": "swanhtetaungp@gmail.com",
  "phrase": "fdajfl;adsjfl;adsd"
}

###
POST http://localhost:8085/api/auth/forgot-password
Content-Type: application/json

{
    "email": "swanhtetaungp@gmail.com"
  }
####
GET http://localhost:8085/api/auth/me?email=swanhtetaungp@gmail.com
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkZXZpY2UiOnsiYnJvd3NlciI6InVua25vd24iLCJkZXRlY3RlZF9hdCI6IjIwMjUtMDQtMTFUMTQ6MDU6MTYuMDU4MjA5KzAyOjAwIiwiZGV2aWNlX3R5cGUiOiJkZXNrdG9wIiwiZmlyc3RfbG9naW4iOiIyMDI1LTA0LTExVDE0OjA1OjE2LjA1ODIwOSswMjowMCIsImxhc3RfbG9naW4iOiIyMDI1LTA0LTExVDE0OjA1OjE2LjA1ODIwOSswMjowMCIsIm9zIjoidW5rbm93biJ9LCJlbWFpbCI6InN3YW5odGV0YXVuZ3BAZ21haWwuY29tIiwiZXhwIjoxNzQ0Mzc0MDE2LCJpYXQiOjE3NDQzNzMxMTYsInJvbGUiOiJhY2Nlc3MiLCJzdWIiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDAifQ._TJAaqk0Pdsh-LyVuRKXfDuiIGa3w3dnUVQLPYOEqag

###
GET http://localhost:8085/api/auth/refresh
Cookie: refresh_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkZXZpY2UiOnsiYnJvd3NlciI6InVua25vd24iLCJkZXRlY3RlZF9hdCI6IjIwMjUtMDQtMTFUMTI6NDQ6NTcuNTA1Mjg3KzAyOjAwIiwiZGV2aWNlX3R5cGUiOiJkZXNrdG9wIiwiZmlyc3RfbG9naW4iOiIyMDI1LTA0LTExVDEyOjQ0OjU3LjUwNTI4NyswMjowMCIsImxhc3RfbG9naW4iOiIyMDI1LTA0LTExVDEyOjQ0OjU3LjUwNTI4NyswMjowMCIsIm9zIjoidW5rbm93biJ9LCJlbWFpbCI6InN3YW5odGV0YXVuZ3BAZ21haWwuY29tIiwiZXhwIjoxNzQ0NDU0Njk3LCJpYXQiOjE3NDQzNjgyOTcsInJvbGUiOiJyZWZyZXNoIiwic3ViIjoiMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAwIn0.ESNwjsmKhxCsxQ3EwDg55T2AGl9Esb3VHscuehczUZw; path=/; HttpOnly; SameSite=Strict
Content-Type: application/json
###

POST  localhost:8085/api/auth/logout
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkZXZpY2UiOnsiYnJvd3NlciI6InVua25vd24iLCJkZXRlY3RlZF9hdCI6IjIwMjUtMDQtMTFUMTM6MTA6MjYuNjgxNDk5KzAyOjAwIiwiZGV2aWNlX3R5cGUiOiJkZXNrdG9wIiwiZmlyc3RfbG9naW4iOiIyMDI1LTA0LTExVDEzOjEwOjI2LjY4MTQ5OSswMjowMCIsImxhc3RfbG9naW4iOiIyMDI1LTA0LTExVDEzOjEwOjI2LjY4MTQ5OSswMjowMCIsIm9zIjoidW5rbm93biJ9LCJlbWFpbCI6InN3YW5odGV0YXVuZ3BAZ21haWwuY29tIiwiZXhwIjoxNzQ0MzcwNzI2LCJpYXQiOjE3NDQzNjk4MjYsInJvbGUiOiJhY2Nlc3MiLCJzdWIiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDAifQ.67aSBt_bOIoQGAAus3aVA6f0wPxof8uQABu2RQkCqBQ
Cookie:   refresh_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkZXZpY2UiOnsiYnJvd3NlciI6InVua25vd24iLCJkZXRlY3RlZF9hdCI6IjIwMjUtMDQtMTFUMTM6MTA6MjYuNjgxNDk5KzAyOjAwIiwiZGV2aWNlX3R5cGUiOiJkZXNrdG9wIiwiZmlyc3RfbG9naW4iOiIyMDI1LTA0LTExVDEzOjEwOjI2LjY4MTQ5OSswMjowMCIsImxhc3RfbG9naW4iOiIyMDI1LTA0LTExVDEzOjEwOjI2LjY4MTQ5OSswMjowMCIsIm9zIjoidW5rbm93biJ9LCJlbWFpbCI6InN3YW5odGV0YXVuZ3BAZ21haWwuY29tIiwiZXhwIjoxNzQ0NDU2MjI2LCJpYXQiOjE3NDQzNjk4MjYsInJvbGUiOiJyZWZyZXNoIiwic3ViIjoiMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAwIn0.a0_xKRJ6Zc4doCKIA0E6lw1W-Hf0prbjBe5RbJ_LM-8; path=/; HttpOnly; SameSite=Strict
Content-Type: application/json

{
    "email": "swanhtetaungp@gmail.com"
}