// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: auth.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserRpcMethod_UserExistenceCall_FullMethodName = "/UserRpcMethod/UserExistenceCall"
)

// UserRpcMethodClient is the client API for UserRpcMethod service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserRpcMethodClient interface {
	UserExistenceCall(ctx context.Context, in *UserExistenceReq, opts ...grpc.CallOption) (*UserExistenceResp, error)
}

type userRpcMethodClient struct {
	cc grpc.ClientConnInterface
}

func NewUserRpcMethodClient(cc grpc.ClientConnInterface) UserRpcMethodClient {
	return &userRpcMethodClient{cc}
}

func (c *userRpcMethodClient) UserExistenceCall(ctx context.Context, in *UserExistenceReq, opts ...grpc.CallOption) (*UserExistenceResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserExistenceResp)
	err := c.cc.Invoke(ctx, UserRpcMethod_UserExistenceCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserRpcMethodServer is the server API for UserRpcMethod service.
// All implementations must embed UnimplementedUserRpcMethodServer
// for forward compatibility.
type UserRpcMethodServer interface {
	UserExistenceCall(context.Context, *UserExistenceReq) (*UserExistenceResp, error)
	mustEmbedUnimplementedUserRpcMethodServer()
}

// UnimplementedUserRpcMethodServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserRpcMethodServer struct{}

func (UnimplementedUserRpcMethodServer) UserExistenceCall(context.Context, *UserExistenceReq) (*UserExistenceResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserExistenceCall not implemented")
}
func (UnimplementedUserRpcMethodServer) mustEmbedUnimplementedUserRpcMethodServer() {}
func (UnimplementedUserRpcMethodServer) testEmbeddedByValue()                       {}

// UnsafeUserRpcMethodServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserRpcMethodServer will
// result in compilation errors.
type UnsafeUserRpcMethodServer interface {
	mustEmbedUnimplementedUserRpcMethodServer()
}

func RegisterUserRpcMethodServer(s grpc.ServiceRegistrar, srv UserRpcMethodServer) {
	// If the following call pancis, it indicates UnimplementedUserRpcMethodServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserRpcMethod_ServiceDesc, srv)
}

func _UserRpcMethod_UserExistenceCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserExistenceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcMethodServer).UserExistenceCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRpcMethod_UserExistenceCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcMethodServer).UserExistenceCall(ctx, req.(*UserExistenceReq))
	}
	return interceptor(ctx, in, info, handler)
}

// UserRpcMethod_ServiceDesc is the grpc.ServiceDesc for UserRpcMethod service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserRpcMethod_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "UserRpcMethod",
	HandlerType: (*UserRpcMethodServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserExistenceCall",
			Handler:    _UserRpcMethod_UserExistenceCall_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
